### ISSUE TITLE
报错null,已填写API key ,已翻墙

### ISSUE THREAD

**Issue by hanbruce** [jinguangyue/AndroidStringsOneTabTranslation#2]
null
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at language_engine.google.GoogleTranslationApi.getTranslationJSON(GoogleTranslationApi.java:78)
	at data.task.GetTranslationTask.getTranslationEngineResult(GetTranslationTask.java:158)
	at data.task.GetTranslationTask.run(GetTranslationTask.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jinguangyue** [comment]
OK 我会检查这个错误
